openapi: 3.0.1
info:
  title: monster-glabrezu
  x-cortex-tag: monster-glabrezu
  x-cortex-custom-metadata:
    alignment: neutral-good
    type: fiend
    challenge_rating: 17
    legendary: false
    armor_class: 12
    hit_points: 157
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-glabrezu
      alias: github-token-test
